/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vut.gui;
import javax.swing.JOptionPane;
import vut.data.Patiant;
import vut.data.DataStorageException;
import vut.data.NotFoundException;
import vut.data.DuplicateException;
import vut.data.Patiant.*;


/**
 *
 * @author A Jonase
 * 
 */
public class PatiantManagementApp extends javax.swing.JFrame {

    private Patiant objPatiant = null;
    /**
     * Creates new form PatiantManagementApp
     */
    public PatiantManagementApp() {
        initComponents();
        
        objPatiant = new Patiant();

        try {
            objPatiant.getConnection();
            JOptionPane.showMessageDialog(null, "Connection established", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (DataStorageException e) {
            JOptionPane.showMessageDialog(this, "Error invalid Numeric value \n" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtIDnumber = new javax.swing.JTextField();
        txtAmountDue = new javax.swing.JTextField();
        btnViewAll = new javax.swing.JButton();
        btnSavePatiant = new javax.swing.JButton();
        btnViewPataint = new javax.swing.JButton();
        btnMoreOptions = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplay = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        radInPatiants = new javax.swing.JRadioButton();
        radOutPatiants = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patiant Data Management App(218253737)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel1.setText("Surname:");

        jLabel2.setText("ID number:");

        jLabel3.setText("Amount Due:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(txtIDnumber)
                    .addComponent(txtAmountDue))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnSavePatiant.setText("Save Patiant");
        btnSavePatiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePatiantActionPerformed(evt);
            }
        });

        btnViewPataint.setText("View Patiant");
        btnViewPataint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPataintActionPerformed(evt);
            }
        });

        btnMoreOptions.setText("More Options....");
        btnMoreOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreOptionsActionPerformed(evt);
            }
        });

        taDisplay.setColumns(20);
        taDisplay.setRows(5);
        jScrollPane1.setViewportView(taDisplay);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of Patiants", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        radInPatiants.setText("In-Patiants");

        radOutPatiants.setText("Out-Patiants");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radInPatiants)
                .addGap(37, 37, 37)
                .addComponent(radOutPatiants)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radInPatiants)
                    .addComponent(radOutPatiants))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewPataint, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMoreOptions)
                                    .addComponent(btnSavePatiant, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSavePatiant, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewPataint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoreOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        header();
        
        try {
            
            taDisplay.append(objPatiant.getAll().toString().replace(",", "").replace("[", "").replace("]", ""));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error invalid Numeric value \n" + ex.getMessage());
        } catch (IllegalArgumentException | NotFoundException e){
        JOptionPane.showMessageDialog(this, "Error!\n" + e.getMessage());
        }
                                         

    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnSavePatiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePatiantActionPerformed
        String surname = txtSurname.getText(); //get data
        String idNr = txtIDnumber.getText();
        PatiantType typeofPatiant = null;
        double amountDue;
        
        if(radInPatiants.isSelected())
                {typeofPatiant = PatiantType.In_Patiant;}
        else
            if(radOutPatiants.isSelected())
            {typeofPatiant = PatiantType.Out_Patiant;}

        try {
            amountDue = Double.parseDouble(txtAmountDue.getText());

            objPatiant = new Patiant(surname, idNr, amountDue, typeofPatiant); //create an object
            objPatiant.addPatiant(objPatiant); //save an object using addPatiant
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error invalid Numeric value \n" + ex.getMessage());
        } catch (IllegalArgumentException | DuplicateException e){
        JOptionPane.showMessageDialog(this, "Error!\n" + e.getMessage());
        }                  
    }//GEN-LAST:event_btnSavePatiantActionPerformed

    private void btnViewPataintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPataintActionPerformed
        header(); 
        String patiantType = JOptionPane.showInputDialog("Enter Type of patiant to view(type in or out)");
        
        try{
         
         taDisplay.append(objPatiant.returnPatiantType(patiantType).toString().replace(",", "").replace("[", "").replace("]", ""));
         
        } catch (NotFoundException e){
        JOptionPane.showMessageDialog(this, "Error! \n" + e.getMessage());}     
    }//GEN-LAST:event_btnViewPataintActionPerformed

    private void btnMoreOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreOptionsActionPerformed
        PatiantDataManulation moreOptions = new PatiantDataManulation();
        moreOptions.setVisible(true);
        
        //PatiantDataManulation.
       //MarksEntryFrame.setTitle("Student Marks Frame");
    }//GEN-LAST:event_btnMoreOptionsActionPerformed

    private void header() {
    taDisplay.setText("ID_Number\tSurname\tType of Patiant\tAmount_Due\n..................................."
    + "..........................................................................................\n");
    }
    
    private void radioGroup(){
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatiantManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatiantManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatiantManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatiantManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatiantManagementApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoreOptions;
    private javax.swing.JButton btnSavePatiant;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton btnViewPataint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radInPatiants;
    private javax.swing.JRadioButton radOutPatiants;
    private javax.swing.JTextArea taDisplay;
    private javax.swing.JTextField txtAmountDue;
    private javax.swing.JTextField txtIDnumber;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}

